export const red = 'red'
export const cellSelected = 'blue'
export const cell = 'grey'
export const titleSelected = 'white'
export const titleDefault = 'black'
export const navBar = 'rgb(36, 36, 36)'
export const background = 'rgb(42, 42, 42)'